name: publish

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check:
    name: Check commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check commit message
        uses: adityaa30/check-commit@master
        with:
          max-header-length: 255

  build-and-run-docker-image:
    name: Docker build
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: |
          docker build -t changeanalyzer:latest .
          docker run --security-opt seccomp=./chrome.json changeanalyzer "--ini=[driver]\ncommand_executor=http://127.0.0.1:9515\nplatform=web\nurl=https://learn.ivves.eu/" -g
          mkdir docker_results
          docker cp $(docker ps -alq):/home/localtester/change-analyzer/recordings ./docker_results
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./docker_results

  release:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    name: Publish
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "semantic-release"
          git config user.name "semantic-release"
          make publish